import { PrismaClient } from "@prisma/client";

interface PermissionSeed {
  code: string;
  name: string;
  description: string;
  module: string;
  resource: string;
  action: string;
  riskLevel: string;
}

const PERMISSIONS: PermissionSeed[] = [
  // ── Authentication ──────────────────────────────────────────────────────
  {
    code: "auth.register",
    name: "Register Account",
    description: "Register a new user account",
    module: "auth",
    resource: "auth",
    action: "register",
    riskLevel: "low",
  },
  {
    code: "auth.login",
    name: "Login",
    description: "Authenticate and obtain access tokens",
    module: "auth",
    resource: "auth",
    action: "login",
    riskLevel: "low",
  },
  {
    code: "auth.logout",
    name: "Logout",
    description: "Invalidate current session",
    module: "auth",
    resource: "auth",
    action: "logout",
    riskLevel: "low",
  },
  {
    code: "auth.refresh",
    name: "Refresh Token",
    description: "Refresh an expired access token",
    module: "auth",
    resource: "auth",
    action: "refresh",
    riskLevel: "low",
  },
  {
    code: "auth.resetPassword",
    name: "Reset Password",
    description: "Request and complete password reset",
    module: "auth",
    resource: "auth",
    action: "resetPassword",
    riskLevel: "medium",
  },
  {
    code: "auth.changePassword",
    name: "Change Password",
    description: "Change own password while authenticated",
    module: "auth",
    resource: "auth",
    action: "changePassword",
    riskLevel: "low",
  },

  // ── Users ───────────────────────────────────────────────────────────────
  {
    code: "users.create",
    name: "Create Users",
    description: "Create new user accounts",
    module: "users",
    resource: "users",
    action: "create",
    riskLevel: "high",
  },
  {
    code: "users.read",
    name: "Read Users",
    description: "View user profile and account details",
    module: "users",
    resource: "users",
    action: "read",
    riskLevel: "medium",
  },
  {
    code: "users.update",
    name: "Update Users",
    description: "Modify user profile information",
    module: "users",
    resource: "users",
    action: "update",
    riskLevel: "medium",
  },
  {
    code: "users.delete",
    name: "Delete Users",
    description: "Permanently delete user accounts",
    module: "users",
    resource: "users",
    action: "delete",
    riskLevel: "critical",
  },
  {
    code: "users.disable",
    name: "Disable Users",
    description: "Deactivate a user account",
    module: "users",
    resource: "users",
    action: "disable",
    riskLevel: "high",
  },
  {
    code: "users.enable",
    name: "Enable Users",
    description: "Reactivate a disabled user account",
    module: "users",
    resource: "users",
    action: "enable",
    riskLevel: "high",
  },
  {
    code: "users.list",
    name: "List Users",
    description: "List all users with filters",
    module: "users",
    resource: "users",
    action: "list",
    riskLevel: "medium",
  },
  {
    code: "users.changeRole",
    name: "Change User Role",
    description: "Change a user's assigned role",
    module: "users",
    resource: "users",
    action: "changeRole",
    riskLevel: "critical",
  },
  {
    code: "users.invite",
    name: "Invite Users",
    description: "Send account invitation to a new user",
    module: "users",
    resource: "users",
    action: "invite",
    riskLevel: "high",
  },

  // ── Roles & Permissions ─────────────────────────────────────────────────
  {
    code: "roles.create",
    name: "Create Roles",
    description: "Create a new custom role",
    module: "roles",
    resource: "roles",
    action: "create",
    riskLevel: "critical",
  },
  {
    code: "roles.read",
    name: "Read Roles",
    description: "View role definitions and assigned permissions",
    module: "roles",
    resource: "roles",
    action: "read",
    riskLevel: "medium",
  },
  {
    code: "roles.update",
    name: "Update Roles",
    description: "Modify role name, description, or permissions",
    module: "roles",
    resource: "roles",
    action: "update",
    riskLevel: "critical",
  },
  {
    code: "roles.delete",
    name: "Delete Roles",
    description: "Delete a custom role",
    module: "roles",
    resource: "roles",
    action: "delete",
    riskLevel: "critical",
  },
  {
    code: "roles.list",
    name: "List Roles",
    description: "List all available roles",
    module: "roles",
    resource: "roles",
    action: "list",
    riskLevel: "low",
  },
  {
    code: "roles.assign",
    name: "Assign Role",
    description: "Assign a role to a user",
    module: "roles",
    resource: "roles",
    action: "assign",
    riskLevel: "high",
  },

  // ── Restaurants (Organizations) ─────────────────────────────────────────
  {
    code: "restaurants.create",
    name: "Create Restaurants",
    description: "Create a new restaurant organization",
    module: "restaurants",
    resource: "restaurants",
    action: "create",
    riskLevel: "high",
  },
  {
    code: "restaurants.read",
    name: "Read Restaurants",
    description: "View restaurant profile and configuration",
    module: "restaurants",
    resource: "restaurants",
    action: "read",
    riskLevel: "low",
  },
  {
    code: "restaurants.update",
    name: "Update Restaurants",
    description: "Update restaurant profile (name, logo, contact)",
    module: "restaurants",
    resource: "restaurants",
    action: "update",
    riskLevel: "medium",
  },
  {
    code: "restaurants.delete",
    name: "Delete Restaurants",
    description:
      "Delete a restaurant organization and all associated data",
    module: "restaurants",
    resource: "restaurants",
    action: "delete",
    riskLevel: "critical",
  },
  {
    code: "restaurants.list",
    name: "List Restaurants",
    description: "List all restaurant organizations",
    module: "restaurants",
    resource: "restaurants",
    action: "list",
    riskLevel: "medium",
  },
  {
    code: "restaurants.activate",
    name: "Activate Restaurant",
    description: "Activate a restaurant from draft or suspended status",
    module: "restaurants",
    resource: "restaurants",
    action: "activate",
    riskLevel: "high",
  },
  {
    code: "restaurants.suspend",
    name: "Suspend Restaurant",
    description: "Suspend an active restaurant",
    module: "restaurants",
    resource: "restaurants",
    action: "suspend",
    riskLevel: "high",
  },
  {
    code: "restaurants.archive",
    name: "Archive Restaurant",
    description: "Archive a restaurant (soft-delete)",
    module: "restaurants",
    resource: "restaurants",
    action: "archive",
    riskLevel: "critical",
  },
  {
    code: "restaurants.settings.read",
    name: "Read Restaurant Settings",
    description: "View restaurant operational settings (timezone, currency, reservation policies)",
    module: "restaurants",
    resource: "settings",
    action: "read",
    riskLevel: "low",
  },
  {
    code: "restaurants.settings.update",
    name: "Update Restaurant Settings",
    description: "Modify restaurant operational settings",
    module: "restaurants",
    resource: "settings",
    action: "update",
    riskLevel: "medium",
  },
  {
    code: "restaurants.reservation-policy.read",
    name: "Read Reservation Policy",
    description: "View reservation policy settings (party size, duration, advance booking, cancellation)",
    module: "restaurants",
    resource: "reservation-policy",
    action: "read",
    riskLevel: "low",
  },
  {
    code: "restaurants.reservation-policy.update",
    name: "Update Reservation Policy",
    description: "Modify reservation policy settings (party size, duration, advance booking, cancellation)",
    module: "restaurants",
    resource: "reservation-policy",
    action: "update",
    riskLevel: "medium",
  },

  // ── Business Hours ───────────────────────────────────────────────────────
  {
    code: "restaurants.business-hours.read",
    name: "Read Business Hours",
    description: "View restaurant business hours and opening periods",
    module: "restaurants",
    resource: "business-hours",
    action: "read",
    riskLevel: "low",
  },
  {
    code: "restaurants.business-hours.update",
    name: "Update Business Hours",
    description: "Modify restaurant business hours and opening periods",
    module: "restaurants",
    resource: "business-hours",
    action: "update",
    riskLevel: "medium",
  },

  // ── Calendar Exceptions ──────────────────────────────────────────────────
  {
    code: "restaurants.calendar-exceptions.read",
    name: "Read Calendar Exceptions",
    description: "View calendar exceptions (holidays, closures, events) for a restaurant",
    module: "restaurants",
    resource: "calendar-exceptions",
    action: "read",
    riskLevel: "low",
  },
  {
    code: "restaurants.calendar-exceptions.create",
    name: "Create Calendar Exceptions",
    description: "Create calendar exceptions for holidays, special openings, closures",
    module: "restaurants",
    resource: "calendar-exceptions",
    action: "create",
    riskLevel: "medium",
  },
  {
    code: "restaurants.calendar-exceptions.update",
    name: "Update Calendar Exceptions",
    description: "Modify existing calendar exceptions",
    module: "restaurants",
    resource: "calendar-exceptions",
    action: "update",
    riskLevel: "medium",
  },
  {
    code: "restaurants.calendar-exceptions.delete",
    name: "Delete Calendar Exceptions",
    description: "Remove calendar exceptions",
    module: "restaurants",
    resource: "calendar-exceptions",
    action: "delete",
    riskLevel: "high",
  },

  // ── Restaurant Assets ───────────────────────────────────────────────────
  {
    code: "restaurants.assets.read",
    name: "Read Restaurant Assets",
    description: "View restaurant assets (logos, covers, gallery images, menus)",
    module: "restaurants",
    resource: "assets",
    action: "read",
    riskLevel: "low",
  },
  {
    code: "restaurants.assets.upload",
    name: "Upload Restaurant Assets",
    description: "Upload new restaurant assets",
    module: "restaurants",
    resource: "assets",
    action: "upload",
    riskLevel: "medium",
  },
  {
    code: "restaurants.assets.delete",
    name: "Delete Restaurant Assets",
    description: "Remove restaurant assets",
    module: "restaurants",
    resource: "assets",
    action: "delete",
    riskLevel: "high",
  },
  {
    code: "restaurants.assets.update",
    name: "Update Restaurant Assets",
    description: "Modify restaurant asset metadata (e.g., set as primary)",
    module: "restaurants",
    resource: "assets",
    action: "update",
    riskLevel: "medium",
  },

  // ── Dining Areas ─────────────────────────────────────────────────────────
  {
    code: "restaurants.dining-areas.create",
    name: "Create Dining Areas",
    description: "Create a new dining area in a restaurant",
    module: "restaurants",
    resource: "dining-areas",
    action: "create",
    riskLevel: "medium",
  },
  {
    code: "restaurants.dining-areas.read",
    name: "View Dining Areas",
    description: "View dining area details and list",
    module: "restaurants",
    resource: "dining-areas",
    action: "read",
    riskLevel: "low",
  },
  {
    code: "restaurants.dining-areas.update",
    name: "Update Dining Areas",
    description: "Modify dining area configuration",
    module: "restaurants",
    resource: "dining-areas",
    action: "update",
    riskLevel: "medium",
  },
  {
    code: "restaurants.dining-areas.archive",
    name: "Archive Dining Areas",
    description: "Archive (soft-delete) a dining area",
    module: "restaurants",
    resource: "dining-areas",
    action: "archive",
    riskLevel: "high",
  },

  // ── Branches ────────────────────────────────────────────────────────────
  {
    code: "branches.create",
    name: "Create Branches",
    description: "Create a new restaurant branch",
    module: "branches",
    resource: "branches",
    action: "create",
    riskLevel: "high",
  },
  {
    code: "branches.read",
    name: "Read Branches",
    description: "View branch details and configuration",
    module: "branches",
    resource: "branches",
    action: "read",
    riskLevel: "low",
  },
  {
    code: "branches.update",
    name: "Update Branches",
    description: "Update branch profile and settings",
    module: "branches",
    resource: "branches",
    action: "update",
    riskLevel: "medium",
  },
  {
    code: "branches.delete",
    name: "Delete Branches",
    description: "Delete a branch and all associated data",
    module: "branches",
    resource: "branches",
    action: "delete",
    riskLevel: "critical",
  },
  {
    code: "branches.list",
    name: "List Branches",
    description: "List all branches within an organization",
    module: "branches",
    resource: "branches",
    action: "list",
    riskLevel: "low",
  },
  {
    code: "branches.configureHours",
    name: "Configure Branch Hours",
    description: "Configure branch operating hours and holidays",
    module: "branches",
    resource: "branches",
    action: "configureHours",
    riskLevel: "medium",
  },
  {
    code: "branches.configurePolicies",
    name: "Configure Branch Policies",
    description: "Configure reservation policies per branch",
    module: "branches",
    resource: "branches",
    action: "configurePolicies",
    riskLevel: "medium",
  },

  // ── Tables ──────────────────────────────────────────────────────────────
  {
    code: "tables.create",
    name: "Create Tables",
    description: "Add a new table to the floor plan",
    module: "tables",
    resource: "tables",
    action: "create",
    riskLevel: "medium",
  },
  {
    code: "tables.read",
    name: "Read Tables",
    description: "View table details and status",
    module: "tables",
    resource: "tables",
    action: "read",
    riskLevel: "low",
  },
  {
    code: "tables.update",
    name: "Update Tables",
    description: "Modify table configuration (capacity, location, zone)",
    module: "tables",
    resource: "tables",
    action: "update",
    riskLevel: "medium",
  },
  {
    code: "tables.delete",
    name: "Delete Tables",
    description: "Remove a table from the floor plan",
    module: "tables",
    resource: "tables",
    action: "delete",
    riskLevel: "high",
  },
  {
    code: "tables.list",
    name: "List Tables",
    description: "List all tables in a branch",
    module: "tables",
    resource: "tables",
    action: "list",
    riskLevel: "low",
  },
  {
    code: "tables.assign",
    name: "Assign Tables",
    description: "Assign a specific table to a reservation",
    module: "tables",
    resource: "tables",
    action: "assign",
    riskLevel: "medium",
  },
  {
    code: "tables.release",
    name: "Release Tables",
    description: "Release a table from a reservation",
    module: "tables",
    resource: "tables",
    action: "release",
    riskLevel: "medium",
  },
  {
    code: "tables.updateStatus",
    name: "Update Table Status",
    description: "Update table occupancy status",
    module: "tables",
    resource: "tables",
    action: "updateStatus",
    riskLevel: "low",
  },
  {
    code: "tables.merge",
    name: "Merge Tables",
    description: "Merge two or more tables into one",
    module: "tables",
    resource: "tables",
    action: "merge",
    riskLevel: "medium",
  },
  {
    code: "tables.split",
    name: "Split Tables",
    description: "Split a merged table back into individual tables",
    module: "tables",
    resource: "tables",
    action: "split",
    riskLevel: "medium",
  },
  {
    code: "tables.disable",
    name: "Disable Tables",
    description: "Mark a table as out of service",
    module: "tables",
    resource: "tables",
    action: "disable",
    riskLevel: "medium",
  },
  {
    code: "tables.configureLayout",
    name: "Configure Table Layout",
    description: "Configure the visual floor plan layout",
    module: "tables",
    resource: "tables",
    action: "configureLayout",
    riskLevel: "medium",
  },

  // ── Reservations ────────────────────────────────────────────────────────
  {
    code: "reservations.create",
    name: "Create Reservations",
    description: "Create a new reservation",
    module: "reservations",
    resource: "reservations",
    action: "create",
    riskLevel: "medium",
  },
  {
    code: "reservations.read",
    name: "Read Reservations",
    description: "View reservation details",
    module: "reservations",
    resource: "reservations",
    action: "read",
    riskLevel: "low",
  },
  {
    code: "reservations.update",
    name: "Update Reservations",
    description: "Modify an existing reservation",
    module: "reservations",
    resource: "reservations",
    action: "update",
    riskLevel: "medium",
  },
  {
    code: "reservations.delete",
    name: "Delete Reservations",
    description: "Delete a reservation from the system",
    module: "reservations",
    resource: "reservations",
    action: "delete",
    riskLevel: "high",
  },
  {
    code: "reservations.cancel",
    name: "Cancel Reservations",
    description: "Cancel a reservation with reason",
    module: "reservations",
    resource: "reservations",
    action: "cancel",
    riskLevel: "medium",
  },
  {
    code: "reservations.confirm",
    name: "Confirm Reservations",
    description: "Confirm a pending reservation",
    module: "reservations",
    resource: "reservations",
    action: "confirm",
    riskLevel: "medium",
  },
  {
    code: "reservations.checkIn",
    name: "Check In Reservations",
    description: "Check in a guest upon arrival",
    module: "reservations",
    resource: "reservations",
    action: "checkIn",
    riskLevel: "low",
  },
  {
    code: "reservations.checkOut",
    name: "Check Out Reservations",
    description: "Check out a guest and release table",
    module: "reservations",
    resource: "reservations",
    action: "checkOut",
    riskLevel: "low",
  },
  {
    code: "reservations.markNoShow",
    name: "Mark No-Show",
    description: "Mark a reservation as no-show",
    module: "reservations",
    resource: "reservations",
    action: "markNoShow",
    riskLevel: "medium",
  },
  {
    code: "reservations.list",
    name: "List Reservations",
    description: "List reservations with filters",
    module: "reservations",
    resource: "reservations",
    action: "list",
    riskLevel: "low",
  },
  {
    code: "reservations.searchAvailability",
    name: "Search Availability",
    description: "Search available time slots",
    module: "reservations",
    resource: "reservations",
    action: "searchAvailability",
    riskLevel: "low",
  },
  {
    code: "reservations.autoAssign",
    name: "Auto-Assign Tables",
    description: "Automatically assign the best available table",
    module: "reservations",
    resource: "reservations",
    action: "autoAssign",
    riskLevel: "low",
  },
  {
    code: "reservations.manageRecurring",
    name: "Manage Recurring Reservations",
    description: "Create and manage recurring reservations",
    module: "reservations",
    resource: "reservations",
    action: "manageRecurring",
    riskLevel: "medium",
  },
  {
    code: "reservations.addNotes",
    name: "Add Reservation Notes",
    description: "Add internal notes to a reservation",
    module: "reservations",
    resource: "reservations",
    action: "addNotes",
    riskLevel: "low",
  },
  {
    code: "reservations.manageWalkIn",
    name: "Manage Walk-Ins",
    description: "Create walk-in reservations",
    module: "reservations",
    resource: "reservations",
    action: "manageWalkIn",
    riskLevel: "medium",
  },
  {
    code: "reservations.overrideBlock",
    name: "Override Reservation Blocks",
    description: "Override reservation blocks or restrictions",
    module: "reservations",
    resource: "reservations",
    action: "overrideBlock",
    riskLevel: "high",
  },

  // ── Customers ───────────────────────────────────────────────────────────
  {
    code: "customers.create",
    name: "Create Customers",
    description: "Create a new customer profile",
    module: "customers",
    resource: "customers",
    action: "create",
    riskLevel: "low",
  },
  {
    code: "customers.read",
    name: "Read Customers",
    description: "View customer profile and visit history",
    module: "customers",
    resource: "customers",
    action: "read",
    riskLevel: "medium",
  },
  {
    code: "customers.update",
    name: "Update Customers",
    description: "Modify customer profile information",
    module: "customers",
    resource: "customers",
    action: "update",
    riskLevel: "medium",
  },
  {
    code: "customers.delete",
    name: "Delete Customers",
    description: "Delete a customer profile",
    module: "customers",
    resource: "customers",
    action: "delete",
    riskLevel: "high",
  },
  {
    code: "customers.list",
    name: "List Customers",
    description: "List customers with search and filters",
    module: "customers",
    resource: "customers",
    action: "list",
    riskLevel: "medium",
  },
  {
    code: "customers.merge",
    name: "Merge Customers",
    description: "Merge duplicate customer profiles",
    module: "customers",
    resource: "customers",
    action: "merge",
    riskLevel: "high",
  },
  {
    code: "customers.flag",
    name: "Flag Customers",
    description: "Flag a customer as high-risk (no-show pattern)",
    module: "customers",
    resource: "customers",
    action: "flag",
    riskLevel: "medium",
  },
  {
    code: "customers.addNotes",
    name: "Add Customer Notes",
    description: "Add notes to a customer profile",
    module: "customers",
    resource: "customers",
    action: "addNotes",
    riskLevel: "low",
  },
  {
    code: "customers.export",
    name: "Export Customers",
    description: "Export customer data",
    module: "customers",
    resource: "customers",
    action: "export",
    riskLevel: "high",
  },

  // ── Notifications ───────────────────────────────────────────────────────
  {
    code: "notifications.send",
    name: "Send Notifications",
    description: "Manually trigger a notification",
    module: "notifications",
    resource: "notifications",
    action: "send",
    riskLevel: "medium",
  },
  {
    code: "notifications.viewLog",
    name: "View Notification Log",
    description: "View notification delivery log",
    module: "notifications",
    resource: "notifications",
    action: "viewLog",
    riskLevel: "low",
  },
  {
    code: "notifications.configureTemplates",
    name: "Configure Notification Templates",
    description: "Configure notification message templates",
    module: "notifications",
    resource: "notifications",
    action: "configureTemplates",
    riskLevel: "medium",
  },
  {
    code: "notifications.configurePreferences",
    name: "Configure Notification Preferences",
    description: "Configure notification preferences per branch",
    module: "notifications",
    resource: "notifications",
    action: "configurePreferences",
    riskLevel: "medium",
  },
  {
    code: "notifications.retry",
    name: "Retry Notifications",
    description: "Retry failed notification delivery",
    module: "notifications",
    resource: "notifications",
    action: "retry",
    riskLevel: "low",
  },

  // ── Reports & Analytics ─────────────────────────────────────────────────
  {
    code: "reports.view",
    name: "View Reports",
    description: "View operational reports on screen",
    module: "reports",
    resource: "reports",
    action: "view",
    riskLevel: "low",
  },
  {
    code: "reports.export",
    name: "Export Reports",
    description: "Export reports as CSV or PDF",
    module: "reports",
    resource: "reports",
    action: "export",
    riskLevel: "medium",
  },
  {
    code: "reports.viewDashboard",
    name: "View Dashboard",
    description: "View the main analytics dashboard",
    module: "reports",
    resource: "reports",
    action: "viewDashboard",
    riskLevel: "low",
  },
  {
    code: "reports.configureMetrics",
    name: "Configure Report Metrics",
    description: "Configure which metrics appear on reports",
    module: "reports",
    resource: "reports",
    action: "configureMetrics",
    riskLevel: "medium",
  },
  {
    code: "reports.schedule",
    name: "Schedule Reports",
    description: "Schedule automated report generation",
    module: "reports",
    resource: "reports",
    action: "schedule",
    riskLevel: "medium",
  },

  // ── Dashboard ───────────────────────────────────────────────────────────
  {
    code: "dashboard.view",
    name: "View Dashboard",
    description: "View the main operational dashboard",
    module: "dashboard",
    resource: "dashboard",
    action: "view",
    riskLevel: "low",
  },
  {
    code: "dashboard.customize",
    name: "Customize Dashboard",
    description: "Customize dashboard widgets and layout",
    module: "dashboard",
    resource: "dashboard",
    action: "customize",
    riskLevel: "low",
  },

  // ── Settings ────────────────────────────────────────────────────────────
  {
    code: "settings.view",
    name: "View Settings",
    description: "View system and branch settings",
    module: "settings",
    resource: "settings",
    action: "view",
    riskLevel: "low",
  },
  {
    code: "settings.updateGeneral",
    name: "Update General Settings",
    description: "Update general settings (name, contact, time zone)",
    module: "settings",
    resource: "settings",
    action: "updateGeneral",
    riskLevel: "medium",
  },
  {
    code: "settings.updateReservationPolicies",
    name: "Update Reservation Policies",
    description: "Update reservation policy settings",
    module: "settings",
    resource: "settings",
    action: "updateReservationPolicies",
    riskLevel: "medium",
  },
  {
    code: "settings.updateNotificationPreferences",
    name: "Update Notification Preferences",
    description: "Update notification preferences",
    module: "settings",
    resource: "settings",
    action: "updateNotificationPreferences",
    riskLevel: "medium",
  },
  {
    code: "settings.updateBusinessHours",
    name: "Update Business Hours",
    description: "Update operating hours and holiday schedule",
    module: "settings",
    resource: "settings",
    action: "updateBusinessHours",
    riskLevel: "medium",
  },
  {
    code: "settings.manageIntegrations",
    name: "Manage Integrations",
    description: "Manage third-party integrations",
    module: "settings",
    resource: "settings",
    action: "manageIntegrations",
    riskLevel: "high",
  },

  // ── Audit Logs ──────────────────────────────────────────────────────────
  {
    code: "audit.read",
    name: "View Audit Logs",
    description: "View audit log entries",
    module: "audit",
    resource: "audit",
    action: "read",
    riskLevel: "high",
  },
  {
    code: "audit.readSensitive",
    name: "View Sensitive Audit Logs",
    description:
      "View sensitive audit entries (auth changes, role changes)",
    module: "audit",
    resource: "audit",
    action: "readSensitive",
    riskLevel: "critical",
  },
  {
    code: "audit.export",
    name: "Export Audit Logs",
    description: "Export audit logs",
    module: "audit",
    resource: "audit",
    action: "export",
    riskLevel: "critical",
  },
  {
    code: "audit.configureRetention",
    name: "Configure Audit Retention",
    description: "Configure audit log retention policy",
    module: "audit",
    resource: "audit",
    action: "configureRetention",
    riskLevel: "critical",
  },

  // ── Organizations (Multi-Tenant) ────────────────────────────────────────
  {
    code: "organizations.create",
    name: "Create Organizations",
    description: "Create a new tenant organization",
    module: "organizations",
    resource: "organizations",
    action: "create",
    riskLevel: "critical",
  },
  {
    code: "organizations.read",
    name: "Read Organizations",
    description: "View organization details",
    module: "organizations",
    resource: "organizations",
    action: "read",
    riskLevel: "high",
  },
  {
    code: "organizations.update",
    name: "Update Organizations",
    description: "Update organization information",
    module: "organizations",
    resource: "organizations",
    action: "update",
    riskLevel: "critical",
  },
  {
    code: "organizations.delete",
    name: "Delete Organizations",
    description: "Delete an organization and all its data",
    module: "organizations",
    resource: "organizations",
    action: "delete",
    riskLevel: "critical",
  },
  {
    code: "organizations.list",
    name: "List Organizations",
    description: "List all organizations in the system",
    module: "organizations",
    resource: "organizations",
    action: "list",
    riskLevel: "critical",
  },
  {
    code: "organizations.manageSubscription",
    name: "Manage Subscription",
    description: "Manage organization subscription and billing",
    module: "organizations",
    resource: "organizations",
    action: "manageSubscription",
    riskLevel: "high",
  },

  // ── System ──────────────────────────────────────────────────────────────
  {
    code: "system.viewHealth",
    name: "View System Health",
    description: "View system health status",
    module: "system",
    resource: "system",
    action: "viewHealth",
    riskLevel: "low",
  },
  {
    code: "system.manageBackup",
    name: "Manage Backups",
    description: "Perform and manage system backups",
    module: "system",
    resource: "system",
    action: "manageBackup",
    riskLevel: "critical",
  },
  {
    code: "system.manageRecovery",
    name: "Manage Recovery",
    description: "Perform system recovery operations",
    module: "system",
    resource: "system",
    action: "manageRecovery",
    riskLevel: "critical",
  },
  {
    code: "system.viewLogs",
    name: "View System Logs",
    description: "View system-level application logs",
    module: "system",
    resource: "system",
    action: "viewLogs",
    riskLevel: "high",
  },
  {
    code: "system.configureGlobal",
    name: "Configure System Settings",
    description: "Configure global system settings",
    module: "system",
    resource: "system",
    action: "configureGlobal",
    riskLevel: "critical",
  },
];

export async function seedPermissions(
  prisma: PrismaClient
): Promise<void> {
  for (const permission of PERMISSIONS) {
    await prisma.permission.upsert({
      where: { code: permission.code },
      update: {
        name: permission.name,
        description: permission.description,
        module: permission.module,
        resource: permission.resource,
        action: permission.action,
        riskLevel: permission.riskLevel,
      },
      create: permission,
    });
  }
}
